<a href="https://colab.research.google.com/github/GauravTiwariTechAnalyst/GT/blob/master/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [ ]:
import numpy as np
a=[10,20,30]
a=np.array(a)
print(a.ndim)
print(a.shape)

print(type(a))

1
(3,)
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=[10,20,30]

print(type(a))

<class 'list'>


In [ ]:
import numpy as np
a=[100,200,300]
#print(a)
a=np.array(a)
print(a)
print(type(a))


[100 200 300]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=[10,20,30]
print(a)
b=np.array(a)
print(type(b))

[10, 20, 30]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
c=np.array([10,20,30],dtype=float)
print(c.shape)

(3,)


In [ ]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9],[12,13,14]]
b=np.array(a)
print(b.ndim)
print(type(b))
print(b.shape)
print(b[3].max())
print(b[1][1])


2
<class 'numpy.ndarray'>
(4, 3)
14
5


In [ ]:
import numpy as np
a=[[1,2,3],[4,5,6]],[[7,8,9],[12,13,14]]
b=np.array(a)
print(b.ndim)
print(type(b))
print(b.shape)
print(b[1][1][2])
print(b[1][1].max())
print(b[0][0].min(),b[0][1].min(),b[1][0].min(),b[1][1].min())


3
<class 'numpy.ndarray'>
(2, 2, 3)
14
14
1 4 7 12


In [ ]:
import numpy as np
b=np.array([[10,20,30],[20,30,60]])
print (b.shape)

(2, 3)


In [ ]:
x=float(110.6)
print(x)

110.6


In [ ]:
import numpy as np
b=np.array([[10,20,30],[20,30,60],[10,20,30]])
print (b)
print(b.shape)

[[10 20 30]
 [20 30 60]
 [10 20 30]]
(3, 3)


In [ ]:
print('Hello')

Hello


In [ ]:
print("Hello")

Hello


In [ ]:
print type('a','b','c')

SyntaxError: ignored